tap "caskroom/cask"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/dupes"
tap "homebrew/php"
tap "homebrew/versions"
brew "openssl"
brew "jansson"
brew "hwloc"
brew "libmicrohttpd"
brew "libuv"
brew "zlib"
brew uninstall "curl"
brew "homebrew/php/php70-pthreads"

